service: pr2-level-importer

package:
  exclude:
    - "layers/**"
    - "stashed/**"

custom:
  bucket: ${self:provider.stage}-pr4-levels

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/pr2/*"

# https://github.com/jwerre/node-canvas-lambda
layers:
  lib64:
    package:
      artifact: layers/canvas-lib64-layer.zip
  canvas:
    package:
      artifact: layers/node10_canvas_layer.zip
  cwebp:
    package:
      artifact: layers/cwebp.zip

functions:
  import-level:
    handler: src/index.handler
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 30 # optional, in seconds, default is 6
    environment:
      BUCKET: ${self:custom.bucket}
      SAVE_TARGET: ${env:SAVE_TARGET, 's3'} # s3 or local
    events:
      - http:
          path: import-from-pr2/{levelId}
          method: get
          request:
            parameters:
               paths:
                 levelId: true
    layers:
     - { Ref: Lib64LambdaLayer }
     - { Ref: CanvasLambdaLayer }
     - { Ref: CwebpLambdaLayer }
